# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 10:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestCases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2017, 11, 20, 10, 31, 44, 821116, tzinfo=utc))),
                ('visitor_control', models.FloatField(blank=True, null=True)),
                ('visitor_variation', models.FloatField(blank=True, null=True)),
                ('conversion_control', models.FloatField(blank=True, null=True)),
                ('conversion_variation', models.FloatField(blank=True, null=True)),
                ('pvalue', models.CharField(blank=True, max_length=10, null=True)),
                ('significance', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
